# Generated by Django 4.2.23 on 2025-08-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0004_alter_userdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
